tinyll: main.c
	gcc -ggdb -ansi -pedantic -Wall -o tinyll-test main.c ../tinyll.c
clean:
	rm -f tinyll-test
	rm -f sort-test
sort: sort-test.c
	gcc -ggdb -ansi -pedantic -Wall  sort-test.c ../tinyll.c -o sort-test
